// Publish
export const BACKEND_URL = "https://server.atbineremlak.com";
// Test area
// export const BACKEND_URL = "http://localhost:4000";
export const cloudName = "dee5jnjoq";
export const uploadPreset = "jkhctkbl";
export const apiKey = "968535658219782";
export const apiSecret = "MEfHMPIDbcq8E1u7_HLBFUFiV40";

export const cepheListesi = ["Batı", "Doğu", "Kuzey", "Güney"];
export const icOzelliklerListesi = [
  "ADSL",
  "Ahşap Doğrama",
  "Akıllı Ev",
  "Alarm (Hırsız)",
  "Alarm (Yangın)",
  "Alaturka Tuvalet",
  "Alüminyum Doğrama",
  "Amerikan Kapı",
  "Amerikan Mutfak",
  "Ankastre Fırın",
  "Asansör",
  "Barbekü",
  "Beyaz Eşya",
  "Boyalı",
  "Bulaşık Makinesi",
  "Buzdolabı",
  "Çamaşır Kurutma Makinesi",
  "Çamaşır Odası",
  "Çelik Kapı",
  "Duşakabin",
  "Duvar Kağıdı",
  "Ebeveyn Banyosu",
  "Fırın",
  "Fiber İnternet",
  "Giyinme Odası",
  "Gömme Dolap",
  "Görüntülü Diafon",
  "Hilton Banyo",
  "İntercom Sistemi",
  "Isıcam",
  "Jakuzi",
  "Kartonpiyer",
  "Kiler",
  "Klima",
  "Küvet",
  "Laminant Zemin",
  "Marley",
  "Mobilya",
  "Mutfak (Ankastre)",
  "Mutfak (Laminant)",
  "Mutfak Doğalgazı",
  "Panjur / Jaluzi",
  "Parke Zemin",
  "PVC Doğrama",
  "Seramik Zemin",
  "Set Üstü Ocak",
  "Spot Aydınlatma",
  "Şofben",
  "Şömine",
  "Teras",
  "Termosifon",
  "Vestiyer",
  "Wi-Fi",
  "Yüz Tanıma",
  "Parmak İzi Tanıma",
];
export const disOzelliklerListesi = [
  "24 Saat Güvenlik",
  "Apartman Görevlisi",
  "Asansör",
  "Buhar Odası",
  "Çocuk Oyun Parkı",
  "Hamam",
  "Hidrofor",
  "Isı Yalıtımı",
  "Jeneratör",
  "Kablo TV",
  "Kamera Sistemi",
  "Kreş",
  "Müstakil Havuz",
  "Otopark (Açık)",
  "Otopark (Kapalı)",
  "Sauna",
  "Ses Yalıtımı",
  "Siding",
  "Spor Alanı",
  "Su Deposu",
  "Tenir Kortu",
  "Uydu",
  "Yangın Merdiveni",
  "Yüzme Havuzu (Açık)",
  "Yüzme Havuzu (Kapalı)",
];
export const muhitListesi = [
  "Alışveriş Merkezi",
  "Market",
  "Semt Pazarı",
  "Belediye",
  "Polis Merkezi",
  "İtfaiye",
  "Eczane",
  "Hastane",
  "Sağlık Ocağı",
  "Cami",
  "Cemevi",
  "Kilise",
  "Denize Sıfır",
  "Plaj",
  "Eğlence Merkezi",
  "Fuar",
  "Park",
  "Havra",
  "İlkokul",
  "Ortaokul",
  "Lise",
  "Üniversite",
  "Spor Salonu",
  "Şehir Merkezi",
];
export const ulasimListesi = [
  "Anayol",
  "Dolmuş",
  "Havaalanı",
  "Metro",
  "Metrobüs",
  "Minibüs",
  "Otobüs Durağı",
  "Sahil",
  "Tren İstasyonu",
];
export const manzaraListesi = [
  "Boğaz",
  "Deniz",
  "Doğa",
  "Göl",
  "Havuz",
  "Park",
  "Yeşil Alan",
  "Şehir",
];
export const konutTipiListesi = [
  "Ara Kat",
  "Ara Kat Dubleks",
  "Bahçe Dubleksi",
  "Bahçe Katı",
  "Bahçeli",
  "Çatı Dubleksi",
  "En Üst Kat",
  "Forleks",
  "Garaj Üstü",
  "Dükkan Üstü",
  "Giriş Katı",
  "Kat Dubleksi",
  "Loft",
  "Müstakil Girişli",
  "Ters Dubleks",
  "Tripleks",
  "Zemin Kat",
];

export const guvenlikListesi = [
  "Alarm",
  "ABS",
  "ASR",
  "ESP",
  "Hava Yastığı (Sürücü)",
  "Hava Yastığı (Yan)",
  "Hava Yastığı (Yolcu)",
  "Immobilizer",
  "Lastik Arıza Göstergesi",
  "Merkezi Kilit",
  "Yokuş Kalkış Desteği",
];
export const icDonanimListesi = [
  "Deri Döşeme",
  "Elektrikli Koltuklar",
  "Hız Sabitleyici",
  "Hidrolik Direksiyon",
  "Isıtmalı Koltuklar",
  "Klima",
  "Otomatik Cam",
  "Start / Stop",
  "Yağmur Sensörü",
  "Yol Bilgisayarı",
];
export const disDonanimListesi = [
  "Alaşım Jant",
  "Çeki Demiri",
  "Elektrikli Aynalar",
  "Far (sis)",
  "Far Sensörü",
  "Far Yıkama Sistemi",
  "Otomatik Kapı",
  "Panoramik Cam Tavan",
  "Park Sensörü",
  "Sunroof",
  "Sürgülü Kapı (çift)",
  "Sürgülü Kapı (tek)",
  "Xenon Far",
];
export const multimedyaListesi = [
  "Android Auto",
  "Apple CarPlay",
  "6+ Hoparlör",
  "Arka Eğlence Paketi",
  "Bluetooth - Telefon",
  "CD / DVD Çalar",
  "CD / DVD Değiştirici",
  "Radio (Kasetçalar)",
  "Radio (MP3 Çalar)",
  "TV / Navigasyon",
];
